name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^2.0.4
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.3.6
  flutter_widget_from_html: ^0.10.3
  go_router: ^7.0.2
  html: ^0.15.4
  http: ^1.1.0
  intl: ^0.18.1
  video_player: ^2.6.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    # - .env
    - assets/images/jar-loading.gif
